version: '3.8'

services:
  app:
    container_name: graphqlsequelizeecom
    image: graphqlsequelizeecom:0.0.1
    build: .
    command: npm start
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST=node_db
    depends_on:
      - node_db
    volumes:
      - .:/src
  node_db:
    container_name: node_db
    image: mysql:5.7
    env_file: ./.env
    restart: unless-stopped
    volumes:
       - db_data:/var/lib/mysql
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_NAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD

volumes:
  db_data: