type Address {
  id: Int!
  storeCustomerStreet: String!
  storeCustomerNeighborhood: String!
  storeCustomerCity: String!
  storeCustomerState: String!
  storeCustomerCountry: String!
  storeCustomerPostalCode: String!
  storeCustomerNumber: Int!
  userId: Int!
  customer: Customer!
}

input AddressInput {
  userId: Int!
  storeCustomerStreet: String!
  storeCustomerNeighborhood: String!
  storeCustomerCity: String!
  storeCustomerState: String!
  storeCustomerCountry: String!
  storeCustomerPostalCode: String!
  storeCustomerNumber: Int!
}

type Query {
  allAddress: [Address!]!
  address(id: Int!): Address!
}
type Mutation {
  createAddress(data: AddressInput!): Address!
}
